source 'http://rubygems.org'
gem 'rack'
gem 'rack-flash3'
gem 'thin'
gem 'sinatra', :require => 'sinatra/base'
gem 'bson_ext'
gem 'haml'
gem 'shotgun'
gem 'cucumber'
gem 'capybara'
gem "iconv"

gem 'data_mapper'
gem 'dm-accepts_nested_attributes', '~> 1.0.0'
gem 'dm-postgres-adapter'
gem 'pg'